- name: Update apt cache
  apt:
    update_cache: yes

- name: Install docker package
  apt:
    name: docker.io
    state: present

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
    state: started
